# This file sets ptrace_scope to 2, which increases security 
# in some circumstances by increasing the restrictions for 
# processes on using ptrace. ptrace can be used by
# (untrusted) processes to access data of other processes
# (for example, a hacked firefox process in a user session would
# be able to ptrace the keyring process and extract passwords
# stored only in memory, or another malicious or hacked process
# can access private data in Firefox).
# 
# ptrace_scope is by default enabled with the setting 1, 
# which mitigates the most likely scenarios that can have
# negative security impacts (the examples above are most likely
# in most contexts not realistic with setting 1): 1 is thus 
# restricting ptrace for most processes.
# In most contexts, ptrace_scope=1 limits ptrace to
# child processes, while there might be exceptions elaborated
# in the links mentioned later in this file.
# 
# In some use cases, it can be useful to increase 
# the restrictions on ptrace with ptrace_scope setting 2,
# Details about the additional restrictions of the setting 2
# are available at the following links:
# https://docs.kernel.org/admin-guide/LSM/Yama.html
# https://wiki.archlinux.org/title/Security#ptrace_scope
#
# While it is likely to not impact most use cases that work 
# with the kernel default (1), there can be some
# use cases that break through using ptrace_scope in the
# setting 2. An example are use cases that use gdb or strace
# but both only for child processes, as this would work with 1
# (as long as both are used only on child processes) but 
# not with 2. You can test the setting 2 temporarily with:
#    sysctl kernel.yama.ptrace_scope=2
# This setting will be automatically reverted to your previous 
# default after reboot
#
# If you want to enable kernel.yama.ptrace_scope with 
# setting 2 permanently, copy or link this file to
# /etc/sysctl.d/10-harden-yama-ptrace.conf
#
# Enabling 10-harden-yama-ptrace.conf has only effect
# if neither 20-yama-ptrace.conf nor 10-default-yama-scope.conf 
# are enabled (nor another file that overrides 10*.conf with 
# kernel.yama.ptrace_scope settings).
# 
# kernel.yama.ptrace_scope can have one of the following values:
#
# 0 - Classic ptrace permissions:
#     A process can PTRACE_ATTACH to any other process running
#     under the same uid, as long as it is dumpable
# 1 - Restricted ptrace:
#     A process must have a predefined relationship with the 
#     inferior it wants to call PTRACE_ATTACH on. 
#     By default, this relationship is that of only its 
#     descendants when the above classic criteria is also met.
# 2 - Admin-only attach:
#     Only processes with CAP_SYS_PTRACE may use ptrace, 
#     either with PTRACE_ATTACH or through children 
#     calling PTRACE_TRACEME.
# 3 - No attach:
#     No process may call ptrace at all. Irrevocable.
#
# Further details in the two mentioned links above.
kernel.yama.ptrace_scope = 2
