# Enabling 20-yama-ptrace.conf will override 
# 10-harden-yama-ptrace.conf, 
# if 10-harden-yama-ptrace.conf is enabled. 
# 
# Enabling 20-yama-ptrace.conf causes security implications and
# should be evaluated before enabling, especially on systems that
# might have untrusted packages or run untrusted processes.
# Details about ptrace_scope are available here:
# https://docs.kernel.org/admin-guide/LSM/Yama.html
# https://wiki.archlinux.org/title/Security#ptrace_scope
# The related information of the Arch wiki apply to Fedora too.
#
# ptrace_scope can be disabled also temporarily rather than 
# permanently, offering a less invasive alternative to 
# 20-yama-ptrace.conf. Disabling ptrace_scope until reboot:
#    sysctl kernel.yama.ptrace_scope=0
# Re-enabling ptrace_scope after it was disabled without rebooting:
#    sysctl kernel.yama.ptrace_scope=1
#
# -----------
#
# The ptrace system call is used for interprocess services,
# communication and introspection (like synchronisation, signaling,
# debugging, tracing and profiling) of processes.
#
# Usage of ptrace is restricted by normal user permissions. Normal
# unprivileged processes cannot use ptrace on processes that they
# cannot send signals to or processes that are running set-uid or
# set-gid. Nevertheless, processes running under the same uid will
# usually be able to ptrace one another: this can have security 
# implications if, e.g., one process is malicious or captured by
# an attacker, whereas another process has private data (such as 
# credentials). The first could exploit ptrace to gain access to 
# the private data of the latter.
#
# Fedora and the upstream kernel default enable the Yama security 
# mechanism which restricts ptrace further, reducing the attack
# surface and possibility for hostile or unexpected/unintended 
# exploitations as described above.
#
# kernel.yama.ptrace_scope can have one of the following values:
#
# 0 - Classic ptrace permissions:
#     A process can PTRACE_ATTACH to any other process running
#     under the same uid, as long as it is dumpable
# 1 - Restricted ptrace:
#     A process must have a predefined relationship with the 
#     inferior it wants to call PTRACE_ATTACH on. 
#     By default, this relationship is that of only its 
#     descendants when the above classic criteria is also met.
# 2 - Admin-only attach:
#     Only processes with CAP_SYS_PTRACE may use ptrace, 
#     either with PTRACE_ATTACH or through children 
#     calling PTRACE_TRACEME.
# 3 - No attach:
#     No process may call ptrace at all. Irrevocable.
#
# Further information, see the two mentioned links above.
#
# The default is 1., which allows tracing of child processes, but
# forbids tracing of arbitrary processes. This allows programs like
# gdb or strace to work when the most common way of having the
# debugger start the debuggee is used:
#    gdb /path/to/program ...
# Attaching to already running programs is NOT allowed:
#    gdb -p ...
# This default setting is suitable for the common case, because it
# reduces the risk that one hacked process can be used to attack other
# processes. (For example, a hacked firefox process in a user session
# will not be able to ptrace the keyring process and extract passwords
# stored only in memory.)
#
# Developers and administrators might want to disable those protections
# to be able to attach debuggers to existing processes. Use
#   sysctl kernel.yama.ptrace_scope=0
# for change the setting temporarily, or copy this file to
# /etc/sysctl.d/20-yama-ptrace.conf to set it for future boots.

kernel.yama.ptrace_scope = 0
